// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6deGgFeryRxtqnB30SVeQRDkUopxkAg',
    appId: '1:299767144888:web:2eb48b9f7450f3ffa46f4d',
    messagingSenderId: '299767144888',
    projectId: 'forksy-5e95d',
    authDomain: 'forksy-5e95d.firebaseapp.com',
    storageBucket: 'forksy-5e95d.firebasestorage.app',
    measurementId: 'G-TBML8N99T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDirNlBCYaHMQYP82z32lGPW-9KB3_opfc',
    appId: '1:299767144888:android:bb2195f69916531ea46f4d',
    messagingSenderId: '299767144888',
    projectId: 'forksy-5e95d',
    storageBucket: 'forksy-5e95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpJZLhfXVD2p6u__DIiTGdHCZhDCJ14vQ',
    appId: '1:299767144888:ios:08c4fa0dee666a67a46f4d',
    messagingSenderId: '299767144888',
    projectId: 'forksy-5e95d',
    storageBucket: 'forksy-5e95d.firebasestorage.app',
    iosBundleId: 'com.aiibd3.forksy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpJZLhfXVD2p6u__DIiTGdHCZhDCJ14vQ',
    appId: '1:299767144888:ios:08c4fa0dee666a67a46f4d',
    messagingSenderId: '299767144888',
    projectId: 'forksy-5e95d',
    storageBucket: 'forksy-5e95d.firebasestorage.app',
    iosBundleId: 'com.aiibd3.forksy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY6deGgFeryRxtqnB30SVeQRDkUopxkAg',
    appId: '1:299767144888:web:3bfbcf6fada57fd4a46f4d',
    messagingSenderId: '299767144888',
    projectId: 'forksy-5e95d',
    authDomain: 'forksy-5e95d.firebaseapp.com',
    storageBucket: 'forksy-5e95d.firebasestorage.app',
    measurementId: 'G-5ZZFKEQ8G4',
  );
}
